/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as PdfdesignerRouteImport } from './routes/pdfdesigner'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PdfdesignerIdRouteImport } from './routes/pdfdesigner/$id'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfdesignerRoute = PdfdesignerRouteImport.update({
  id: '/pdfdesigner',
  path: '/pdfdesigner',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfdesignerIdRoute = PdfdesignerIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PdfdesignerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/pdfdesigner': typeof PdfdesignerRouteWithChildren
  '/users': typeof UsersRoute
  '/pdfdesigner/$id': typeof PdfdesignerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/pdfdesigner': typeof PdfdesignerRouteWithChildren
  '/users': typeof UsersRoute
  '/pdfdesigner/$id': typeof PdfdesignerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/pdfdesigner': typeof PdfdesignerRouteWithChildren
  '/users': typeof UsersRoute
  '/pdfdesigner/$id': typeof PdfdesignerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/pdfdesigner'
    | '/users'
    | '/pdfdesigner/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/pdfdesigner'
    | '/users'
    | '/pdfdesigner/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/pdfdesigner'
    | '/users'
    | '/pdfdesigner/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PdfdesignerRoute: typeof PdfdesignerRouteWithChildren
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdfdesigner': {
      id: '/pdfdesigner'
      path: '/pdfdesigner'
      fullPath: '/pdfdesigner'
      preLoaderRoute: typeof PdfdesignerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdfdesigner/$id': {
      id: '/pdfdesigner/$id'
      path: '/$id'
      fullPath: '/pdfdesigner/$id'
      preLoaderRoute: typeof PdfdesignerIdRouteImport
      parentRoute: typeof PdfdesignerRoute
    }
  }
}

interface PdfdesignerRouteChildren {
  PdfdesignerIdRoute: typeof PdfdesignerIdRoute
}

const PdfdesignerRouteChildren: PdfdesignerRouteChildren = {
  PdfdesignerIdRoute: PdfdesignerIdRoute,
}

const PdfdesignerRouteWithChildren = PdfdesignerRoute._addFileChildren(
  PdfdesignerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PdfdesignerRoute: PdfdesignerRouteWithChildren,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
